### ISSUE TITLE
Can't connect to C3

### ISSUE THREAD

**Issue by GoobertFroobert** [DoogiePC/EDawg878#11]
![2019-06-02_18 28 04](https://user-images.githubusercontent.com/51301784/58768257-76ee5500-8566-11e9-97bd-be2d2e704492.png)

I cannot connect to C3 without being kicked into the server selection screen directly after getting into C3, please help. It's the only C# world I care about, and it's really bothering me.

I've tried numerous times to reset my internet connection, modem, and have restarted my PC many times, and on every other C# server, I can connect, all but C3, it is so annoying.

**Comment by DoogiePC** [comment]
Please enter your username

**Comment by DoogiePC** [comment]
Known issue, ProtocolSupport plugin needs updating.

**Comment by GoobertFroobert** [comment]
> Known issue, ProtocolSupport plugin needs updating.

Okay, thanks for the quick response. I appreciate the help. I'll be posting all of my issues here from now on, this was pretty effective after all.

**Comment by GoobertFroobert** [comment]
> Known issue, ProtocolSupport plugin needs updating.

Actually, it broke again. I did /p home and it did it again, can't join C3. :c

**Comment by DoogiePC** [comment]
Duplicate of #14
