### ISSUE TITLE
TheRiceLord's WorldEdit BUG

### ISSUE THREAD

**Issue by TheRiceLord** [DoogiePC/EDawg878#17]
**Where**

C1 (assuming all creative servers)

**Describe the bug**

World Edit's copy and paste feature have been bugged to being very limited.

**To Reproduce**

1. As an example, build a house with decorated interiors including doors, carpets, end rods, beds, etc..
2. Copy and paste this selected house and you will expect the majority of the interior not to be pasted.

**Expected behaviour**

Before, copy and paste was simple as it pasted every item selected with no error but clearly, this is not evident anymore.

**Comment by DoogiePC** [comment]
Fixed, AsyncWorldedit config. Disabled "#Block set (every block set operation)"
