### ISSUE TITLE
/Plot clear, not working.

### ISSUE THREAD

**Issue by GildedBird** [DoogiePC/EDawg878#18]
**Where**
C1, C2, C3

**Describe the bug**
Whenever you type /plot clear, it says you don't have permission. Meaning it doesn't allow you to clear your plot.

**To Reproduce**
Steps to reproduce the behaviour:
1. /plot clear

**Expected behaviour**
I expect the plot to be cleared, or get the command to confirm clearing the plot, which I don't get either.

**Screenshots**
Attempting to type /plot clear
https://gyazo.com/31ffd0bae071312fdd0db5e972f0b032

Lacking permission.
https://gyazo.com/a85c04e36a31dbc6d33d21f46ec860e0

**Additional context**
Several players are unable to type /plot clear.

**Comment by DoogiePC** [comment]
Plot clear has been disabled until the 1.14.2 lag issues are fixed.
