### ISSUE TITLE
TheRiceLord_'s Feature request

### ISSUE THREAD

**Issue by TheRiceLord** [DoogiePC/EDawg878#19]
**Brief description of the idea:**

Allow plot owners to control more plot settings for newcomers.

**What server should it be on? (creative/survival)**

Creative

**A detailed description of the idea, what it does, why it should be added:**

My plot and many others are purely exploration-based which sometimes thirst for restrictions...
Which is why I have come to the conclusion of allowing plot owners more control of newcomers; their restrictions.
1. _Game mode_
Simple yet effective. Any newcomers inside the plot boundaries are instantly locked into a specified game mode and commands such as /fly cannot change their abilities.
Only effects newcomers and not trusted/added members of the plot.
2. _PVP_ 
Very self-explanatory. Setting the plots PVP setting which would be related to their survival game mode.

**Any benefits:**

Allows much more roleplay ideas and possibilities for creative exploration without 'cheating'

**Any negatives:**

People flying around plots may experience difficulty if they're constantly changing game mode which may be irritating.

**Any extra info:**

Commands could be something like /p gamemode 0

**Comment by DoogiePC** [comment]
The following command has been added:
/plot flag set gamemode survival/creative/adventure
(Sets the game mode for everyone on the plot)

The following command already exists
/plot flag set pvp true/false
(true means allow pvp, false means block pvp)
