### ISSUE TITLE
Chat Glitch in C2

### ISSUE THREAD

**Issue by Zuluku25** [DoogiePC/EDawg878#22]
**Where**
Where does the bug occur, which server? C2

**Describe the bug**
When trying to talk in messages, staff chat, or local. It does not allow the user to use these commands and gives a red error message.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to C2
2. Do /local, /msg, or /sc

**Expected behaviour**
I expected to have a message go to the users I intended it to go to.

**Screenshots**
Down below I put a screenshot of the error that shows up.
https://i.imgur.com/0Nh6Hat.png

**Additional context**

**Comment by DoogiePC** [comment]
Cannot reproduce the error, was likely fixed.
