### ISSUE TITLE
Voting not registrating in C2

### ISSUE THREAD

**Issue by Zuluku25** [DoogiePC/EDawg878#23]
**Where**
Where does the bug occur, which server? C2

**Describe the bug**
I've tried voting, and so have other users. After voting nothing shows in chat and the voting credits remain the same.

**To Reproduce**
Steps to reproduce the behaviour:
1. Do /vote
2. Click a link
3. Register your vote with your username

**Expected behaviour**
I expected to have the vote register, show in chat. and gain voting credits

**Screenshots**
N/A

**Additional context**

**Comment by DoogiePC** [comment]
Fixed, credits now show up on all servers.
