### ISSUE TITLE
/r Permission problem

### ISSUE THREAD

**Issue by Shaunaaaa** [DoogiePC/EDawg878#25]
**Where**
Everywhere within the server (c1/c2/c3/s1)

**Describe the bug**
Noticed that /r isn't working due to saying "insufficient permission" every time someone uses it. seems like a permission problem or something like that. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go on c1/c2/c3/s1
2. have someone to message and then try doing /r back.

**Expected behaviour**
I expected to use the command to work as I was replying back to a msg, but it suddenly just stopped working.

**Screenshots**
Screenshot of the chat once I do the command.
https://imgur.com/DdtM9bG

**Comment by DoogiePC** [comment]
Fixed, thanks for reporting.
