### ISSUE TITLE
Everytime you CTRL+Middle Mouse Button a sign it crashes your game

### ISSUE THREAD

**Issue by TonPixSA** [DoogiePC/EDawg878#26]
**Describe the crash**
Nothing has to be on the sign, it just crashes once you do it, and send you to the hub.

**To Reproduce**
If we are to reproduce what caused the crash to fix it, what should we do.
1. Place a sign.
2. CTRL + Middle Mouse Button Click the sign

**Comment by DoogiePC** [comment]
We've only seen this happen on C3 due to allowing 1.13.2 and below to join

**Comment by TonPixSA** [comment]
Happened on C2

**Comment by TonPixSA** [comment]
> We've only seen this happen on C3 due to allowing 1.13.2 and below to join


It happened on C2 though

**Comment by DoogiePC** [comment]
It is the anti-nbt filter that blocks potentially harmful items. It seems to detect signs as harmful if they have NBT on them which they can be, just dont ctrl+middle click signs.
