### ISSUE TITLE
C2 Login issue

### ISSUE THREAD

**Issue by Chubssss** [DoogiePC/EDawg878#27]
**Where**
C2

**Describe the bug**
Whenever I try to login to C2 it says the usual 'Loading' and 'Building terrain' that appears on screen when loading a world but then kicks me off the whole server claiming that the connection was lost or that I need to relog or more commonly it tells me that the connection to the game was lost.

**To Reproduce**
Steps to reproduce the behaviour:
1. ...
2. ...

**Expected behaviour**
I expected to be able to login to C2 normally as it had been working fine the previous day.

**Screenshots**

**Additional context**
I am able to login to C1 and C3 fine, although C2 will not let me join. I've tried to tpa to a friend who was in c2 and it wouldnt let me join and tried joining C1 first then doing /c2 and that didnt work either.

**Comment by DoogiePC** [comment]
You haven't given any info, such as your username or any screenshots of when it kicked you to hub.
