### ISSUE TITLE
Entities not allowed?

### ISSUE THREAD

**Issue by MsSkins** [DoogiePC/EDawg878#28]
**Describe the lag issue**
I cant place minecarts, armourstands and other things like that on my c3 plots

**To Reproduce**
Steps to reproduce the behaviour:
1. Try placing a minecart on my 4th plot on c3

Does anyone else have this problem please drop it in the comments

**Comment by DoogiePC** [comment]
Entities aren't broken, after looking at your 4th plot, your plot has reached the maximum amount of entities allowed so no more can be spawned.
