### ISSUE TITLE
S1 World Joining

### ISSUE THREAD

**Issue by Mireiia** [DoogiePC/EDawg878#29]
**Where**
Where does the bug occur, which server? C1, C2 etc.
S1

**Describe the bug**
A player can't access their friend's survival world. Whenever they join, they get kicked out of it and they are sent back to their own survival world.

**To Reproduce**
Steps to reproduce the behaviour:
/

**Expected behaviour**
Being able to join other people's worlds without being kicked back to your own survival world.

**Screenshots**
![S1 glitch](https://user-images.githubusercontent.com/52569590/60720216-57ae6300-9f2a-11e9-81c5-1e93ada311f7.png)

**Additional context**
/

**Comment by DoogiePC** [comment]
Not enough info given, you haven't said who the friend is or what command they tried.
