### ISSUE TITLE
Playing on different minecraft versions

### ISSUE THREAD

**Issue by archietxr** [DoogiePC/EDawg878#30]
I have noticed that a bug occurs in C1.
I have been playing on the server using 1.12.2 and today I was playing and there was a reboot. After this reboot occurred, I haven't been able to load onto C1, which is where my current build that I would like to continue is in. Whenever I clicked on the C1 block when I joined the server initially, it would first say that I'm already in the server, and then after 2 or 3 clicks, I would be sent to C2 instead. I then tried using the command ./c1 so I can join C1 but it sends me back to the server selection (the blocks) and says that I'm using an outdated version of Minecraft.

I just don't understand what is happening because your server promotes that you can play with 1.14.3 or older and 1.12.2 isn't an extremely old version.

**Comment by DoogiePC** [comment]
Sometimes older version support is removed from C1 for testing, you should really be on 1.14.3
