### ISSUE TITLE
Sitting Issue

### ISSUE THREAD

**Issue by Zuluku25** [DoogiePC/EDawg878#9]
**Where**
Where does the bug occur, which server? C1, C2 etc.
C1, C2, and C3
**Describe the bug**
Whenever you try to sit down on carpet, stairs, or anything of the sorts it does not let you sit like it used too. 
**To Reproduce**
Steps to reproduce the behaviour:
1. Place carpet/stairs
2. Right click on it

**Expected behaviour**
I expected to sit down on the carpet/stairs.
**Screenshots**

**Additional context**

**Comment by DoogiePC** [comment]
Removed the "[Rifleschairs](https://www.spigotmc.org/resources/rifles-chairs-1-13-x.58809/)" plugin and replaced with "[Betterchairs](https://www.spigotmc.org/resources/better-chairs.18705)" plugin
